import { Category, ChallengeDay, Course } from './types';

export const COURSES: Course[] = [
  {
    id: 'c1',
    title: '소라2 광고 영상 만들기 1',
    description: '소라2를 활용한 광고 영상 제작의 첫 번째 단계를 배워봅니다.',
    thumbnail: 'https://picsum.photos/400/225?random=1',
    videoUrl: 'https://vimeo.com/1143902952',
    duration: '5분',
    difficulty: 'Easy',
    category: Category.OFFICE,
    isPopular: true,
    learningPoints: [],
  },
  {
    id: 'c2',
    title: '소라2 광고 영상 만들기 2',
    description: '소라2를 활용한 광고 영상 제작의 두 번째 단계를 배워봅니다.',
    thumbnail: 'https://picsum.photos/400/225?random=2',
    videoUrl: 'https://vimeo.com/1143869802',
    duration: '5분',
    difficulty: 'Easy',
    category: Category.OFFICE,
    isPopular: true,
    learningPoints: [],
  },
  {
    id: 'c3',
    title: '소라2 광고 영상 만들기 3',
    description: '소라2를 활용한 광고 영상 제작의 세 번째 단계를 배워봅니다.',
    thumbnail: 'https://picsum.photos/400/225?random=3',
    videoUrl: 'https://vimeo.com/1143870389',
    duration: '5분',
    difficulty: 'Easy',
    category: Category.OFFICE,
    isPopular: true,
    learningPoints: [],
  },
  {
    id: 'c4',
    title: '소라2 광고 영상 만들기 4',
    description: '소라2를 활용한 광고 영상 제작의 네 번째 단계를 배워봅니다.',
    thumbnail: 'https://picsum.photos/400/225?random=4',
    videoUrl: 'https://vimeo.com/1143870234',
    duration: '5분',
    difficulty: 'Easy',
    category: Category.OFFICE,
    learningPoints: [],
  },
  {
    id: 'c5',
    title: '소라2 광고 영상 만들기 5',
    description: '소라2를 활용한 광고 영상 제작의 다섯 번째 단계를 배워봅니다.',
    thumbnail: 'https://picsum.photos/400/225?random=5',
    videoUrl: 'https://vimeo.com/1143870113',
    duration: '5분',
    difficulty: 'Easy',
    category: Category.OFFICE,
    learningPoints: [],
  },
  {
    id: 'c6',
    title: '소라2 광고 영상 만들기 6',
    description: '소라2를 활용한 광고 영상 제작의 여섯 번째 단계를 배워봅니다.',
    thumbnail: 'https://picsum.photos/400/225?random=6',
    videoUrl: 'https://vimeo.com/1143869970',
    duration: '5분',
    difficulty: 'Easy',
    category: Category.OFFICE,
    learningPoints: [],
  },
  {
    id: 'c7',
    title: '소라2 광고 영상 만들기 7',
    description: '소라2를 활용한 광고 영상 제작의 일곱 번째 단계를 배워봅니다.',
    thumbnail: 'https://picsum.photos/400/225?random=7',
    videoUrl: 'https://vimeo.com/1143903137',
    duration: '5분',
    difficulty: 'Easy',
    category: Category.OFFICE,
    learningPoints: [],
  },
  {
    id: 'c8',
    title: '소라2 광고 영상 만들기 8',
    description: '소라2를 활용한 광고 영상 제작의 여덟 번째 단계를 배워봅니다.',
    thumbnail: 'https://picsum.photos/400/225?random=8',
    videoUrl: 'https://vimeo.com/1143903214',
    duration: '5분',
    difficulty: 'Easy',
    category: Category.OFFICE,
    learningPoints: [],
  },
  {
    id: 'c9',
    title: '소라2 광고 영상 만들기 9',
    description: '소라2를 활용한 광고 영상 제작의 아홉 번째 단계를 배워봅니다.',
    thumbnail: 'https://picsum.photos/400/225?random=9',
    videoUrl: 'https://vimeo.com/1143903358',
    duration: '5분',
    difficulty: 'Easy',
    category: Category.OFFICE,
    learningPoints: [],
  },
  {
    id: 'c10',
    title: '소라2 광고 영상 만들기 10',
    description: '소라2를 활용한 광고 영상 제작의 열 번째 단계를 배워봅니다.',
    thumbnail: 'https://picsum.photos/400/225?random=10',
    videoUrl: 'https://vimeo.com/1143903464',
    duration: '5분',
    difficulty: 'Easy',
    category: Category.OFFICE,
    learningPoints: [],
  },
  {
    id: 'c11',
    title: '소라2 광고 영상 만들기 11',
    description: '소라2를 활용한 광고 영상 제작의 열한 번째 단계를 배워봅니다.',
    thumbnail: 'https://picsum.photos/400/225?random=11',
    videoUrl: 'https://vimeo.com/1143903547',
    duration: '5분',
    difficulty: 'Easy',
    category: Category.OFFICE,
    learningPoints: [],
  },
  {
    id: 'c12',
    title: '소라2 광고 영상 만들기 12',
    description: '소라2를 활용한 광고 영상 제작의 열두 번째 단계를 배워봅니다.',
    thumbnail: 'https://picsum.photos/400/225?random=12',
    videoUrl: 'https://vimeo.com/1143903756',
    duration: '5분',
    difficulty: 'Easy',
    category: Category.OFFICE,
    learningPoints: [],
  },
  {
    id: 'c13',
    title: '소라2 광고 영상 만들기 13',
    description: '소라2를 활용한 광고 영상 제작의 열세 번째 단계를 배워봅니다.',
    thumbnail: 'https://picsum.photos/400/225?random=13',
    videoUrl: 'https://vimeo.com/1143903982',
    duration: '5분',
    difficulty: 'Easy',
    category: Category.OFFICE,
    learningPoints: [],
  },
  {
    id: 'c14',
    title: '소라2 광고 영상 만들기 14',
    description: '소라2를 활용한 광고 영상 제작의 열네 번째 단계를 배워봅니다.',
    thumbnail: 'https://picsum.photos/400/225?random=14',
    videoUrl: 'https://vimeo.com/1143904098',
    duration: '5분',
    difficulty: 'Easy',
    category: Category.OFFICE,
    learningPoints: [],
  },
  {
    id: 'c15',
    title: '소라2 광고 영상 만들기 15',
    description: '소라2를 활용한 광고 영상 제작의 마지막 단계를 배워봅니다.',
    thumbnail: 'https://picsum.photos/400/225?random=15',
    videoUrl: 'https://vimeo.com/1143904335',
    duration: '5분',
    difficulty: 'Easy',
    category: Category.OFFICE,
    learningPoints: [],
  },
];

export const CHALLENGES: ChallengeDay[] = [
  { day: 1, title: 'AI에게 "안녕" 인사하기', description: '아무 AI 챗봇을 열고 인사를 건네보세요.', status: 'active' },
  { day: 2, title: '저녁 메뉴 추천받기', description: '오늘 냉장고에 있는 재료를 알려주고 메뉴를 추천받으세요.', status: 'locked' },
  { day: 3, title: '감사 이메일 초안 쓰기', description: '동료에게 보낼 감사 메일을 AI에게 써달라고 하세요.', status: 'locked' },
  { day: 4, title: '여행 계획 세우기', description: '가고 싶은 여행지의 1일 코스를 짜달라고 해보세요.', status: 'locked' },
  { day: 5, title: '시 한 편 짓기', description: '좋아하는 단어 3개를 주고 시를 써달라고 하세요.', status: 'locked' },
  { day: 6, title: '영어 문장 번역하기', description: '간단한 한국어 문장을 영어로 번역해달라고 하세요.', status: 'locked' },
  { day: 7, title: 'AI 그림 생성해보기', description: '무료 이미지 생성 도구를 사용해 그림을 만들어보세요.', status: 'locked' },
  { day: 8, title: '회의록 요약하기', description: '긴 회의 내용을 AI에게 요약해달라고 해보세요.', status: 'locked' },
  { day: 9, title: '아이디어 브레인스토밍', description: 'AI와 함께 새로운 아이디어를 만들어보세요.', status: 'locked' },
  { day: 10, title: '코드 설명 듣기', description: '간단한 코드를 보여주고 설명을 들어보세요.', status: 'locked' },
  { day: 11, title: '이력서 작성 도움받기', description: 'AI에게 이력서 문구를 다듬어달라고 하세요.', status: 'locked' },
  { day: 12, title: '맞춤형 학습 계획', description: '배우고 싶은 주제의 학습 계획을 짜보세요.', status: 'locked' },
  { day: 13, title: 'SNS 게시글 작성', description: 'AI와 함께 멋진 게시글을 작성해보세요.', status: 'locked' },
  { day: 14, title: 'AI 활용 사례 정리', description: '지난 14일간 배운 내용을 정리해보세요.', status: 'locked' },
];